CREATE DATABASE PTZU;

USE PTZU;

CREATE TABLE USUARIO (
	ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR (50),
    CORREOE VARCHAR (50),
    USERNAME VARCHAR (50),
    GENERO INT,
    PFP LONGTEXT,
    FECNAC DATE
);

CREATE TABLE EQUIPO (
	ID_EQUIPO INT AUTO_INCREMENT PRIMARY KEY,
    PKMN1 INT,
    PKMN2 INT,
    PKMN3 INT,
    PKMN4 INT,
    PKMN5 INT,
    PKMN6 INT,
    ID_USUARIO INT,
    
    FOREIGN KEY (ID_USUARIO) REFERENCES 		USUARIO (ID_USUARIO)
);

CREATE TABLE OBJETOS (
	ID_OBJETO INT AUTO_INCREMENT PRIMARY KEY,
    OBJ1 INT,
    OBJ2 INT,
    OBJ3 INT,
    OBJ4 INT,
    OBJ5 INT,
    OBJ6 INT,
    ID_EQUIPO INT,
    
    FOREIGN KEY (ID_EQUIPO) REFERENCES
    EQUIPO (ID_EQUIPO)
);

