CREATE DATABASE PTZP;

USE PTZP;

CREATE TABLE REGION (
	ID_REG INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR (30)
);

CREATE TABLE TIPO (
	ID_TIPO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR (30)
);

CREATE TABLE TIPO2 (
	ID_TIPO2 INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR (30)
);

CREATE TABLE PKMN (
	ID_POKE INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR (50),
    NUMERO INT,
    DESCR TEXT,
    ID_REG INT,
    ID_TIPO INT,
    ID_TIPO2 INT,
    
    FOREIGN KEY (ID_REG) REFERENCES
    REGION (ID_REG),
    
    FOREIGN KEY (ID_TIPO) REFERENCES
    TIPO (ID_TIPO),
    
    FOREIGN KEY (ID_REG) REFERENCES
    TIPO2 (ID_TIPO2)    
);